import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const hatolie = localFont({
  src: "./fonts/Hatolie.ttf",
  variable: "--font-hatolie-new",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway-new",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hatolie.variable} ${raleway.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
